### ISSUE TITLE
User bug report - cannot find location

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet-mobile#155]
"I have now tried 3 or 4 times to use the new app. Unfortunately it has failed on each occasion to find the location, whereas the old one is 100% successful. Therefore I cannot use it. Needless to say both are on the same phone, an iPhone 5"

Let me know if you need this user's contact details to ask for more information.

**Comment by Gemmamysoc** [comment]
User feedback:

"Well done on introducing a phone app.  However, it is constantly
crashing - mostly because the GPS function does not seem to work.
And this morning it will not recognise postcodes either - I just get
a message "There was a problem looking up your location" when I
insert a full (and valid) postcode.  Great idea but can you fix the
bugs?  Thanks a lot." 

"Using an iPhone 6 running the latest software (iOS8.1.3 currently)."

**Comment by dracos** [comment]
Closing as out of date, not enough info.
