### ISSUE TITLE
User feedback: Creation of Windows app

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/fixmystreet-mobile#180]
Feedback from user in Oct 2014:

"I would be grateful if you could develop an app for Windows Phone."

**Comment by Gemmamysoc** [comment]
User feedback: 

"Hello There, I have a windows smart phone and wondered if you were
planning to develop an app for this platform?"

**Comment by thomasforth** [comment]
Just as an update to this.

I spent a couple of hours looking at the source, and it's really nice. But, it's in backbone.js (I think). I've never worked with this before, though I'm pretty good with javascript so I could learn. The existing code will be portable to Windows (Phones, Tablets, Desktop) with very few tweaks but I'd need help with the backbone bits.

The other option is to use the API and write a proper native client. This would work on Window Phones, Tablets, and Laptops/Desktop. I wrote the original FixMyStreet app for Symbian (yes, that long ago) so I already have a good idea how the API works (not that it matters, mySociety APIs are always great).

There are two options here if we want to create a Windows FixMyStreet.

0. Someone is already working on this and I don't need to do anything.
1. I get in touch with a main developer of the current app, and maybe spend a day doing the Windows port?
2. I start a new project using the FixMyStreet API that delivers a Native Windows (Modern) app.

What do people think? Is this the right place to have the discussion? Is anyone interested?

**Comment by struan** [comment]
Hi,

As far as I'm aware no one is working on this. At the moment we don't really have any time internally to devote to this but I'm happy to answer any questions you have if you want to look at option 2.

Of course if you want to do 3 then you're more than welcome to do that and again, I'm happy to answer questions. There's a few points where the API is a bit less than optimal I'm afraid, mostly around user authentication.

**Comment by Gemmamysoc** [comment]
User feedback:

"Could we have an app for Windows 8 please."

**Comment by thomasforth** [comment]
I got a few evenings together to look at this and got FMS running on Windows. There are bugs, but no show-stoppers. I expect that using the Phonegap 3.6 branch of the project will fix many of them for free.

A reminder that this is very early progress and that I have quite a lot of other work on at the moment. Please don't expect a release very soon.

![fms_onwindows](https://cloud.githubusercontent.com/assets/606821/6461043/539fa5ee-c194-11e4-8079-32d961d8b4a6.png)

**Comment by TomSteinberg** [comment]
Woo!

**Comment by thomasforth** [comment]
An update on this so I don't forget.

I'm working with the existing code in Phonegap 4.x and there are 5 big bugs. I've fixed 3, worked around 1, and need to look at 1 more.

1. **Unsafe code execution errors** can be fixed by using a newer version of jQuery and/or including the winstore-jscompat.js shim by Microsoft.
2. **Location services don't work.**  Install the `org.apache.cordova.geolocation` plugin.
3. **The webview bounces so you can't scroll the map.** This is fixable by adding the following style `<style>html {overflow:hidden;-ms-content-zooming: none;}</style>` to index.html
4. **Pinch to zoom doesn't work on the map.** This may be a simple fix like point 3, but after a few hours trying I'm not so sure. It may be a problem with OpenLayers. This seems to have been fixed in newer versions. I'm not familiar with the OpenLayers build and deploy system so this might be too big a job for me to fix. For now, I've re-enabled the OpenLayers zoom buttons as an unpleasant workaround.
5. **Camera and photos don't work**. The `org.apache.cordova.camera` plugin installs fine and that allows the camera to launch but the existing UI doesn't deal with this properly. I'm not sure how to fix this yet.

**Comment by Gemmamysoc** [comment]
Great work Thomas! Any more updates? Just had another FMS user ask if a FMS Window app exists - so there's definitely people out there who will use it :)

**Comment by Gemmamysoc** [comment]
User feedback:

"I was just wondering when you will produce an App for the current windows phones?"

**Comment by thomasforth** [comment]
Hi Gemma,

I'm afraid that unless I can find some funding to do this I won't be able to make time for it for at least a couple of months. Problems 4 and 5 are just too big to figure out as a favour.

Sorry,

Tom

**Comment by Gemmamysoc** [comment]
User feedback:

"I note that you have an app for IOS and
android, however I use a Windows phone and the app is not currently
available, do you have any plans to release the app for Windows?"

**Comment by Gemmamysoc** [comment]
Hey @thomasforth ! How's it going? We just had another request from a user for a Windows app, as you can see above :) If you fancy working more on this, let us know how we can help!

**Comment by dracos** [comment]
This app no longer in use, moved to PWA/wrapper. This should theoretically then work in the Microsoft store etc...
