### ISSUE TITLE
Facebook error

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/fixmystreet-mobile#187]
See: https://twitter.com/seawolf/status/541324502786146304

"Do u know bout this on FMS Android when loading "More Details" on any report? OK goes back to map"

![b4mrwvhicaexx7x](https://cloud.githubusercontent.com/assets/944656/5337265/7f4896f6-7ebe-11e4-9938-985795534e3b.jpg)

**Comment by seawolf** [comment]
I'm that Twitterer what reported this issue; I'd seen the MySociety twitter acct so reported it there as I didn't know you had a public issue tracker.

Anyway: I can replicate this by:

* opening the app (Android v4.3)
* moving to the nearest (or any) report (pin on the map)
* tapping it to show the information bubble
* clicking *More Details*

No back button involved. I'm using my home broadband with no issues; this happens each time on that and 3G.

I'll see if it happens on my other Android device (v4.1 possibly) and report back.

Thanks :)

**Comment by Gemmamysoc** [comment]
More user feedback:

"I installed the Fix My Street Android app today. I reported a
problem and uploaded a photo. As soon as it has uploaded I get an
application error saying this:

"There was a network error.
(https://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.fixmystreet.com%2Freport%2FF657941&send=false&layout=button_count&width=90&show_faces=false&action=like%colorscheme=light&font&height=21)"

Why is the app trying auto-like something on Facebook I posted to
Fix My Street. I do not want any link between Fix My Street and
Facebook. I don't have the Facebook app installed because it wants
far too many permissions and it is far too large for an app. Can you
explain what is going on?

Also, when I check my reports in the app and the little bubble
appears with "More Details" in it, I click on that and I get the
same error as above."

**Comment by seawolf** [comment]
> Why is the app trying [to] auto-like something on Facebook ..?

That got me thinking.

The URL that appears in the error box in the app also appears in the HTML of the report view page, specifically the Share button:

```html
   <div id="report-share" class="hidden-js" align="center">
        <a href="https://twitter.com/share" class="twitter-share-button" data-text="I just reported &lsquo; [REPORT TITLE] &rsquo;" data-via="fixmystreet" data-related="mysociety" data-count="none" data-dnt="true">Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.fixmystreet.com%2Freport%2F [REPORT ID] &amp;send=false&amp;layout=button_count&amp;width=90&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:90px; height:21px;" allowTransparency="true"></iframe>
    </div>
```

**Comment by dracos** [comment]
This app no longer in use, moved to PWA.
