### ISSUE TITLE
blank/gray map on launching

### ISSUE THREAD

**Issue by loran750** [mysociety/fixmystreet-mobile#198]
hello

when I launch the app, i have a blank/gray map.
I have to zoom out in order to have the map displayed, which correspond to a map of 500 meters/1640 feet.
The consequence : i cannot zoom in the map if I want to have a better precision.

It occurs on iPhone and on Android.

Any idea ?

regards
![img_0338](https://cloud.githubusercontent.com/assets/2526608/9001601/cb271bc0-3759-11e5-91bd-6098629d0f30.jpg)
![img_0337](https://cloud.githubusercontent.com/assets/2526608/9001600/cb248838-3759-11e5-9674-f28381e69edf.jpg)

**Comment by dracos** [comment]
Are you trying to adapt the app for France? You will have to update the code so that it works in non-UK setting, the code on master is currently UK specific. 

I see a couple of commits on branches that fix this, e.g. https://github.com/mysociety/fixmystreet-mobile/commit/2b61987addccca46871b23952ce3508610aee7de (switches to OSM in non-UK) and https://github.com/mysociety/fixmystreet-mobile/commit/00cb6c2c6790b7fe2aaab1849cff61cccacaf67d (stays with Bing, doesn't try to load UK-only tiles) but nothing on master as yet. You can wait for something to be merged, or adapt the code yourself.

**Comment by loran750** [comment]
Hi Dracos

yes. I can make it work for all but for that bug on the map.
If I understand well, when you zoom IN you change the map layer from Bing to Google (or another one?), that's why it becomes blank ?

I will try with the commits, to see if I can keep on Bing only, or switch to OSM, as you adviced.

regards

**Comment by dracos** [comment]
Yes, it switches to our own mySociety tile server at a zoomed in level, which only works in the UK. This code is found around https://github.com/mysociety/fixmystreet-mobile/blob/8fd15b58733c51d7f001f9eac66b7d03830ec0b4/src/js/map-bing-ol.js#L90 that does this. It would be good if the app let you pick between Bing/OSM/UK.

Note we are currently working on the app in other ways to update it to e.g. Phonegap 3 as I understand it so that it will be able to work, I'll ask someone to leave a current update on progress on https://github.com/mysociety/fixmystreet-mobile/issues/196

**Comment by JenMysoc** [comment]
Hi Laurent! Out of interest are you working with Gregory from fixmystreet.fr ?

**Comment by loran750** [comment]
hi JenMysoc

no, i'm working on another one. Currently, on the web side, I'm covering the 36 658 towns in France. It's okay for now. I make a cobrands for any town that would like to use it. For the others, it's on the main cobrand.

And now i'm working on the mobile app.

regards

**Comment by loran750** [comment]
hello all

for information it works perfectly with the 2 commit pages you gave me.

Thank you for your quick and effective support !
regards

**Comment by dracos** [comment]
This is properly fixed by #223 now, with a configuration variable to set the map type.
