### ISSUE TITLE
Some icons missing

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet-mobile#217]
Some I'm definitely sure about (no delete mark on drafts page), some I'm not sure (gap by Home top left).
Android 5.1, latest public version.

**Comment by stevenday** [comment]
This was interesting!

For posterity:

It turns out we had a bit of a funky icon css setup - we had two sets of stylesheets (18px and 36px) for icons, which were @imported in our custom jquery mobile theme with a hi-dpi targetting media query to put the bigger ones in place for screens with enough dpi. However, the css for the large icons was a bit weird, because it didn't scale the background image to actually force the hidpi nature of them and it changed the sizes/positioning of all the sprites - almost as if it was actually intended to just be for bigger icons, not hi-def ones.

To make things more confusing, something about the @import/media query in the jqm theme meant that ios devices didn't ever load the second, wrongly scaled css, so by a fluke combination of other factors (various extra styles in other css files that seem to have been put in over the years to fix bugs with the icons), they got a decent combination of icon size, scaled background and correct placing of icons for retina icons to work ok. Android wasn't so lucky, so the icons weren't showing because we were using half of the styles for making them hi-dpi and half for making them big 36px icons.

To further confuse things, over time we'd put in lots of extra bits of css to swap icons around (using the black versions instead of white etc), but with *different* media queries to target them.

In the end I've been able to remove lots of our custom overrides, simplify the theme's css considerably, and it all seems to work on every scale of device I can test it with.
