### ISSUE TITLE
Issue with 'common password' check firing when logged in?

### ISSUE THREAD

**Issue by dracos** [mysociety/fixmystreet-mobile#270]
Although this user does also get confirmation emails for each report, even though they are logged in, so I don't really know what's going on and it's possible the common password error firing is part of the same thing, if it's taking him through logged-out flow rather than logged-in. Or something. Weird.

> I just wrote up a report on my phone, logged in, finished the rest of the details, hit "Confirm name" and got "Invalid report - Please choose a less commonly-used password". No option to change the password at that point without backing out of the reporting process. More annoyingly, I changed the password via your website (which hadn't complained about it), and still can't submit. I had to go back, click to log in again, log in with the new password, then back to the confirm name screen and submit again - it worked eventually (albeit requiring a confirmation email even though it's a long-time active account, which I believe I reported as a bug before).

**Comment by fixmystreetfr** [comment]
ON IOS : I tried this too and failed to send the repport. and this is bad because i do not want ask for change original passwords of all users on our fixmytreet platform. 

the test was done with this option in my config.js 
    LOGIN_REQUIRED: true, and false,
    SKIP_CONFIRM_REPORT: true,
    PASSWORD_MIN_LENGTH: 0, and 6
    PASSWORD_CHECK_COMMON: false and true

When  LOGIN_REQUIRED: true : i finished to complete questionnary and click next, i moved to a buggy "View details" page showing the map greyed. Im locked here and only can go back to previous page.

When  LOGIN_REQUIRED: false: i tried all the options (the three sent options) with a connected existing user with a common password or new ones not connected. failed for all with LOGIN_REQUIRED: false and using a common password. No information about constraints was viewed.

The only way to get it worked was changed the password  on the fixmystreet platform to a complicated one, it works with this config.js options.

the option "PASSWORD_CHECK_COMMON: false" is not working nothing ?
How can we fully desactivate constraints check ?

thanks.

**Comment by dracos** [comment]
Sorry I don't entirely follow what you've written, but firstly `LOGIN_REQUIRED` is an internal config option, which means only people already registered can use it, you do not want to use that. `PASSWORD_CHECK_COMMON: false` means it doesn't do app-side checking, it doesn't affect the server.

This sounds like a bug, it's not meant to do this. It should only be checking the password if you're setting it in the app (using the "I'd like to set a password" option) at the time you make the report, not if you're logged in or logging in with password that's already set, or "don't want to set a password". If it is erroring about common password on other options, that is a bug.

**Comment by fixmystreetfr** [comment]
hello,
To be more clear,  with the option "PASSWORD_MIN_LENGTH: 0, or 6 or PASSWORD_CHECK_COMMON: false or true", when i used or create a common password, i'll finish on a failed page or found a not workable "send button".
There is no information provided by the app about that password constraint when doing the create workflow.

best regards,

**Comment by fixmystreetfr** [comment]
if this logs could be in relation with the bug ? 

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x28051ada0 H:[_UIModernBarButton:0x14fd6c9e0'OK']-(16)-|   (active, names: '|':_UIButtonBarButton:0x14fd6be50 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2018-12-14 03:03:43.384047+0100 XXXXX807:195209] THREAD WARNING: ['Geolocation'] took '49.148193' ms. Plugin should use a background thread.
2018-12-14 03:04:50.202345+0100 XXXX[807:195209] THREAD WARNING: ['File'] took '10.437988' ms. Plugin should use a background thread.
2018-12-14 03:05:24.288465+0100 XXXX[807:195209] SubmitConfirmView.afterRender

**Comment by fixmystreetfr** [comment]
i've restart from a fresh git clone and retried tests in english only all seems to works..
Maybe something came wrong with the localization part or Xcode update or between the chair and keyboard.

**Comment by LouiseMySociety** [comment]
Dave A started to review last sprint. Needs further investigation
