### ISSUE TITLE
Presentation of grouped categories is awkward

### ISSUE THREAD

**Issue by davea** [mysociety/fixmystreet-mobile#283]
Since we've introduced category groups the experience on the app has been less than ideal:

> Ordering of categories in westminster is weird. things without groups then things with maybe? even though many (e.g. abandoned bike) only has the one category under it.

**Comment by ValeriaPL** [comment]
Regarding this observation/commentary about the current operation of the menu of categories in mobile, I make the following proposal and / or request for consultancy:

**First.** Propose to the fixmystreet mobile development team to adopt a more contemporary menu model, present in most current apps (PWA's in Ionic or, Cordova, etc.), that is, those that integrate icons or "masonry" styles. I enclose the idea in the attached .jpg graphic.

**Two.** In that sense, I ask you to guide me to start developing this idea in the mobile code. I have been studying that the flow follows from details.html to details.js and maybe some other dependencies.
I wish you could please explain the related process flow, for example:
a) The "API" that retrieves the categories of the central site.
b) The treatment in the data structures (variables, arrays, objects, etc.) of the flow of categories and subcategories.
c) The JavaScript flow for the on-screen rendering of the categories and subcategories.

In such a way that I can understand the flow that you have programmed so that I can proceed to develop any of the menus that I am proposing. I have the knowledge of JS programming but I don't fully understand their algorithm / process flow behind the way they have programmed it.

I would thank you a lot.

Thank you so much.
Valery PL

![contemporary-menus-proposed-fixmystreet](https://user-images.githubusercontent.com/53241192/85366602-4ff61e80-b4ed-11ea-9150-c10c7ad057f4.jpg)

**Comment by ValeriaPL** [comment]
Regarding this observation/commentary about the current operation of the menu of categories in mobile, I make the following proposal and / or request for consultancy:

First. Propose to the fixmystreet mobile development team to adopt a more contemporary menu model, present in most current apps (PWA's in Ionic or, Cordova, etc.), that is, those that integrate icons or "masonry" styles. I enclose the idea in the attached .jpg graphic.

Two. In that sense, I ask you to guide me to start developing this idea in the mobile code. I have been studying that the flow follows from details.html to details.js and maybe some other dependencies.
I wish you could please explain the related process flow, for example:
a) The "API" that retrieves the categories of the central site.
b) The treatment in the data structures (variables, arrays, objects, etc.) of the flow of categories and subcategories.
c) The JavaScript flow for the on-screen rendering of the categories and subcategories.

In such a way that I can understand the flow that you have programmed so that I can proceed to develop any of the menus that I am proposing. I have the knowledge of JS programming but I don't fully understand their algorithm / process flow behind the way they have programmed it.

I would thank you a lot.

Thank you so much.
Valery PL

![contemporary-menus-proposed-fixmystreet](https://user-images.githubusercontent.com/53241192/85366951-f3473380-b4ed-11ea-8d44-ecb1ae00926a.jpg)

**Comment by dracos** [comment]
This app no longer in use; new one does multiple levels for picking category
